import React, { useRef, useEffect, useState } from 'react';
import { 
  Bold, Italic, Underline, 
  AlignLeft, AlignCenter, AlignRight, AlignJustify,
  List, ListOrdered 
} from 'lucide-react';

interface RichTextEditorProps {
  value: string;
  onChange: (val: string) => void;
  placeholder?: string;
}

export const RichTextEditor: React.FC<RichTextEditorProps> = ({ value, onChange, placeholder }) => {
  const editorRef = useRef<HTMLDivElement>(null);
  const lastHtml = useRef(value);
  const [isFocused, setIsFocused] = useState(false);

  // Sync external changes (e.g. when selecting a different question)
  useEffect(() => {
    if (editorRef.current && value !== lastHtml.current) {
      editorRef.current.innerHTML = value || '';
      lastHtml.current = value;
    }
  }, [value]);

  const handleInput = () => {
    if (editorRef.current) {
      let html = editorRef.current.innerHTML;
      // Normalize empty tags generated by browsers to empty string
      if (html === '<br>' || html === '<p><br></p>' || html === '<div><br></div>' || html === '<div></div>') {
        html = '';
      }
      lastHtml.current = html;
      onChange(html);
    }
  };

  const executeCommand = (command: string, value: string = '') => {
    document.execCommand(command, false, value);
    handleInput();
    // Refocus the editor area to ensure the cursor stays active
    if (editorRef.current) {
      editorRef.current.focus();
    }
  };

  const toolbarActions = [
    { icon: <Bold size={15} />, command: 'bold', title: 'Chữ đậm (Ctrl+B)' },
    { icon: <Italic size={15} />, command: 'italic', title: 'Chữ nghiêng (Ctrl+I)' },
    { icon: <Underline size={15} />, command: 'underline', title: 'Gạch chân (Ctrl+U)' },
    { type: 'separator' },
    { icon: <AlignLeft size={15} />, command: 'justifyLeft', title: 'Căn lề trái' },
    { icon: <AlignCenter size={15} />, command: 'justifyCenter', title: 'Căn giữa' },
    { icon: <AlignRight size={15} />, command: 'justifyRight', title: 'Căn lề phải' },
    { icon: <AlignJustify size={15} />, command: 'justifyFull', title: 'Căn đều' },
    { type: 'separator' },
    { icon: <List size={15} />, command: 'insertUnorderedList', title: 'Danh sách ký hiệu (Bullets)' },
    { icon: <ListOrdered size={15} />, command: 'insertOrderedList', title: 'Danh sách số (Numbering)' },
  ];

  return (
    <div 
      className="rich-text-editor-container" 
      style={{
        border: isFocused ? '1px solid var(--primary-color)' : '1px solid var(--border-color)',
        boxShadow: isFocused ? '0 0 0 2px rgba(1, 117, 194, 0.15)' : 'none',
        borderRadius: '8px',
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        transition: 'border-color 0.2s, box-shadow 0.2s',
      }}
    >
      {/* Toolbar */}
      <div 
        className="rte-toolbar" 
        style={{
          display: 'flex',
          flexWrap: 'wrap',
          gap: '2px',
          padding: '6px 8px',
          borderBottom: '1px solid var(--border-color)',
          backgroundColor: '#F8FAFC',
          alignItems: 'center',
          userSelect: 'none'
        }}
      >
        {toolbarActions.map((action, idx) => {
          if (action.type === 'separator') {
            return (
              <div 
                key={`sep-${idx}`} 
                style={{ 
                  width: '1px', 
                  height: '16px', 
                  backgroundColor: 'var(--border-color)', 
                  margin: '0 6px' 
                }} 
              />
            );
          }
          return (
            <button
              key={idx}
              type="button"
              // Crucial: prevent focus loss from editor area on click
              onMouseDown={(e) => {
                e.preventDefault();
                executeCommand(action.command!);
              }}
              title={action.title}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                width: '28px',
                height: '28px',
                border: 'none',
                borderRadius: '4px',
                background: 'transparent',
                cursor: 'pointer',
                color: 'var(--text-secondary)',
                transition: 'background-color 0.15s, color 0.15s',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = 'rgba(1, 117, 194, 0.08)';
                e.currentTarget.style.color = 'var(--primary-color)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = 'transparent';
                e.currentTarget.style.color = 'var(--text-secondary)';
              }}
            >
              {action.icon}
            </button>
          );
        })}
      </div>

      {/* Editor Content Area */}
      <div
        ref={editorRef}
        contentEditable
        className="explanation-content"
        onInput={handleInput}
        onFocus={() => setIsFocused(true)}
        onBlur={() => {
          setIsFocused(false);
          handleInput(); // ensure parent gets the latest when user moves away
        }}
        style={{
          minHeight: '100px',
          maxHeight: '260px',
          overflowY: 'auto',
          padding: '12px',
          outline: 'none',
          fontSize: '0.95rem',
          lineHeight: '1.5',
          color: 'var(--text-primary)',
          backgroundColor: 'transparent',
        }}
        {...{ placeholder }}
      />
    </div>
  );
};
